// Rewrites the catalogue mirror at the bottom of supabase/schema.sql from
// src/store/Catalog.ts, so the prices the database enforces cannot drift
// from the ones the store shows. `npm run catalog-sql`, then re-run the
// schema (or just its last statement) in the Supabase SQL editor.

import { readFileSync, writeFileSync } from "node:fs";
import { BUNDLES, ITEMS, NAME_COST } from "../src/store/Catalog";

const FILE = "supabase/schema.sql";
const MARK = "-- ------------------------------------------------------- catalogue mirror";

const rows: string[] = [];
for (const i of ITEMS) if (i.crowns > 0) rows.push(`  ('${i.id}', ${i.crowns}, 'item')`);
for (const b of BUNDLES) rows.push(`  ('${b.id}', ${b.crowns}, 'bundle')`);
rows.push(`  ('name', ${NAME_COST}, 'name')`);

const sql = readFileSync(FILE, "utf8");
const at = sql.indexOf(MARK);
if (at < 0) throw new Error("marker not found in schema.sql");
const tail =
  `${MARK}\n-- Generated by \`npm run catalog-sql\` from src/store/Catalog.ts. Do not edit by hand.\n` +
  `insert into public.catalog (item_id, crowns, kind) values\n${rows.join(",\n")}\n` +
  `on conflict (item_id) do update set crowns = excluded.crowns, kind = excluded.kind;\n`;
writeFileSync(FILE, sql.slice(0, at) + tail);
console.log(`catalog: ${rows.length} rows written to ${FILE}`);
